[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
solver = { path = "../../crates/solver" }
md5 = "0.7"
itertools = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"